#On macbook connect by IP directly, server will not be visible in discovery
version: '3'
services:
    samba:
        # image: dperson/samba
        build: ./
        ports:
            # - '137:137/udp'
            # - '138:138/udp'
            - '139:139/tcp'
            - '139:139/udp'
            - '445:445/tcp'
            - '445:445/udp'
        volumes: 
            - /z1s/back:/z1s/back
            - /z3s/canFail:/z3s/canFail
        restart: always
        command: -r -p -u "smbnas;silakanmasuk" -s "back;/z1s/back;no;no;no;smbnas,smbnas,smbnas,smbnas" -s "canFail;/z3s/canFail;no;no;no;smbnas,smbnas,smbnas,smbnas"
# -r disable recyle bin
# -p reset permissions
# -u user
# -s share